### ISSUE TITLE
Issue when install fairseq

### ISSUE THREAD

**Issue by gaozhiguang** [xieyxclack/factual_coco#1]
Hi, thanks for the nice work!
When i try to install the fairseq in this project, i have this issue, do you know how to solve it?
![image](https://user-images.githubusercontent.com/34132216/158020169-fb1c7480-629e-4819-9a35-627b7b6a9bfd.png)

**Comment by xieyxclack** [comment]
It is a little hard to know why it fails from the upload figure, Maybe you can build up a virtual environment accordingly and try to install again :)

**Comment by XuelinLuu** [comment]
> Hi, thanks for the nice work! When i try to install the fairseq in this project, i have this issue, do you know how to solve it? ![image](https://user-images.githubusercontent.com/34132216/158020169-fb1c7480-629e-4819-9a35-627b7b6a9bfd.png)

Hi, u should modify the read encode='utf-8' in line 43
like this`with open("README.md", encoding='utf-8') as f:
    readme = f.read()`

**Comment by gaozhiguang** [comment]
> It is a little hard to know why it fails from the upload figure, Maybe you can build up a virtual environment accordingly and try to install again :)

**Comment by gaozhiguang** [comment]
> > Hi, thanks for the nice work! When i try to install the fairseq in this project, i have this issue, do you know how to solve it? ![image](https://user-images.githubusercontent.com/34132216/158020169-fb1c7480-629e-4819-9a35-627b7b6a9bfd.png)
> 
> Hi, u should modify the read encode='utf-8' in line 43 like this`with open("README.md", encoding='utf-8') as f: readme = f.read()`

Hi, thanks. It can be installed now.
